version: '3'

services:
  app:
    image: ppaquin/authz-api:latest
    ports:
      - "8004:8000"
    depends_on:
      - db
    environment:
      - ROCKET_ADDRESS=0.0.0.0
      - ROCKET_PORT=8000
      - MONGO_URI=mongodb://db:27017
    networks:
      - authz-network
  db:
    image: mongo:latest
    #    ports:
    #      - "27017:27017"
    volumes:
      - authz_db_data:/data/db
    networks:
      - authz-network
volumes:
  authz_db_data:
networks:
  authz-network:
#    driver: bridge